server:
  port: 8000

spring:
  application:
    name: boot-cli
# mysql 配置
  datasource:
    username: root
    password: hhasdasd@
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
#redis 配置
  redis:
    host: localhost
    port: 6379
    password: YuitRedis@123+
    jedis:
      pool:
        max-active: 8 # 连接词最大链接数
        max-wait: -1 # 连接池最大阻塞等待时间（负数代表没有限制）
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
    timeout: 0 # 链接超时时间 （ms）
logging.level.org.springframework.security: DEBUG

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper # mapper 文件路径
   # type-aliases-package: club.yuit.boot.entity
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: uuid
      db-type: mysql  # 3.0 版本的必须配置 不然无法启动 nested exception is com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: GlobalConfigUtils setMetaData Fail !  Cause:java.lang.NullPointerException
boot:
  oauth:
    token-store-type: jwt
